### ISSUE TITLE
[BUG] Crash when trying to add new JVM

### ISSUE THREAD

**Issue by hellidox** [QuestCraftPlusPlus/PojavLauncher#16] opened 2022-02-21 22:05 UTC
### Describe the bug

Pressing "New VM" crashes the app, something to do with the alert handler

### The log file and images/videos

logs can't save, no storage perms

### Steps To Reproduce

```markdown
Start Pojav-Settings-Java Tweaks-Runtime manager-Add New-crash
```

### Expected Behavior

I expect to be able to add a JRE

### Platform

```markdown
- Device model: Quest 2
- CPU architecture: aarch64
- Android version: Quest 2 latest
- PojavLauncher version: Latest build (gh-actions)
```

**Comment by Flamgop** [comment] 2022-02-21 22:11
These builds contain the JVM 17, but this bug is known. We are planning on fixing this in the future.

**Comment by ghost** [comment] 2022-02-21 22:24
I'm also getting what I think is a similar error, and it seems to be caused by the Launcher not having access to my files. (Sorry for Google Photos links, it was the fastest way) https://photos.app.goo.gl/zuELfCmtxzWu3vtZ8

**Comment by hellidox** [comment] 2022-02-21 22:47
@GiraffeMan3125 Yes, that's the same error.
Strangely, pojav doesn't request storage permissions, and trying to start a version (1.18.1) says it can't find a compatible version of Java.

**Comment by Sinnn3000** [comment] 2022-02-21 22:49
Sideload zarchiver and give it storage permissions. this is because pojav doesnt have access to the file browser built into quest so u have to use a separate one.

it worked for me let me know how it goes for you.

**Comment by hellidox** [comment] 2022-02-21 22:50
Give what storage perms? Zarchiver or pojav?

**Comment by Sinnn3000** [comment] 2022-02-21 22:50
zarchiver, sorry for not specifying

edit: it should ask when you first start it

**Comment by Flopgop** [comment] 2022-09-12 02:05
Closing this, you shouldn't be adding a new JVM anyway.

**Closed as not planned by Flopgop** 2022-09-12 02:05 UTC
Labels: bug
